---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - магазин SPA-приложение, которое не перезагружает страницу
  - магазин должен корректно отображаться и быть адаптирован к мобильным устройствам
  - корзина должна храниться в сессии браузера 
  - на странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без неё
implicit:
  - магазину необходимо иметь страницу оплаты  
  - корзина должна сохранять добавленные в неё товары до их удаления пользователем 
  - сайт должен иметь удобный и понятный интерфейс 
  - сайт должен иметь возможность выбора языка  
